from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns=[
    path('',views.index,name='index'),
    path('aboutus',views.about,name='about'),
    path('product',views.product,name='works'),
    path('contact',views.contact,name='contact'),
    path('ultratech',views.ultratech1,name='ultratech'),
    path('astral',views.astr,name='astral'),
    path('berger',views.berg,name='berger'),
    path('steel',views.st,name='steel'),
    path('rmc',views.rc,name='ur'),
    path('aggregates',views.agre,name='aggregates'),
    path('cera',views.bf,name='cera'),
    path('tatawiron',views.tw,name='tatawiron'),
    path('watertank',views.wt,name='water'),
    path('constructionsloution',views.cs,name='solu'),
    path('waterproofing',views.wp,name='proof'),
    path('tileadhesive',views.ta,name='tile'),
    path('jointmortar',views.jm,name='joint'),
    path('birlawhite',views.bw,name='birla'),
    path('kdm',views.kd,name='kdm'),
    path('bf',views.bff,name='bf'),
    path('ca1',views.caa,name='ca1'),
    path('hft',views.hff,name='hft'),
    path('hef',views.haf,name='hef'),
    path('kif',views.kitchen,name='kif'),
    path('oa',views.ali,name='oa'),
    path('qt',views.qut,name='qt'),
    path('sensor',views.sens,name='sensor'),
    path('sw',views.sww,name='sw'),
    path('slf',views.sl,name='slf'),
    path('sp',views.snpp,name='sp'),
    path('ks',views.kits,name='ks'),
    path('bathacss',views.bas,name='bathacss'),
    path('cist',views.cit,name='cist'),
    path('ea',views.ew,name='ea'),
    path('fl',views.flu,name='fl'),
    path('kds',views.kr,name='kds'),
    path('seat',views.stt,name='seat'),
    path('special',views.sp,name='special'),
    path('uri',views.urr,name='uri'),
    path('wb',views.bs,name='wb'),
    path('ws',views.sw,name='ws'),
    path('btub',views.btu,name='btub'),
    path('btubwirl',views.btuw,name='btubwirl'),
    path('csp',views.cp,name='csp'),
    path('pp',views.ppp,name='pp'),
    path('swc',views.swcc,name='swc'),
    path('swp',views.swpp,name='swp'),
    path('shp',views.shpp,name='shp'),
    path('steam',views.stm,name='steam'),
    #path('info/',views.inn),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)