# Generated by Django 3.0.6 on 2020-05-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultratech',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
