# Generated by Django 3.0.6 on 2020-05-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200528_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultratech',
            name='text1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ultratech',
            name='text2',
            field=models.CharField(max_length=1000),
        ),
    ]
