# Generated by Django 3.0.6 on 2020-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200528_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='form1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=10)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
