# Generated by Django 3.0.6 on 2020-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_form1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='number',
            field=models.IntegerField(),
        ),
    ]
