# Generated by Django 3.0.6 on 2020-05-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form1',
        ),
        migrations.DeleteModel(
            name='logo',
        ),
    ]
