# Generated by Django 3.0.6 on 2020-05-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_ultratechrmc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ultratechRmc',
        ),
    ]
