# Generated by Django 3.0.6 on 2020-05-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Message',
            field=models.CharField(max_length=100),
        ),
    ]
