# Generated by Django 3.0.6 on 2020-07-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_showercubicles_showerpanels_showerpartition_steamshowerroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='astral',
            new_name='upvc',
        ),
    ]
