# Generated by Django 3.0.6 on 2020-07-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_upvc1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upvc',
        ),
    ]
